## library() calls go here
library(seuratTools)
library(conflicted)
conflicts_prefer(dplyr::desc)
conflicts_prefer(dplyr::n_distinct)
library(dotenv)
library(targets)
library(tarchetypes)
library('tidyverse')
library('fs')
library('readxl')
library(numbat)
library(Seurat)
library(patchwork)
library(msigdbr)
library(glue)
library(ggplotify)
library(rlang)
library(clusterProfiler)
library(DOSE)
library(writexl)
library(magick)
library(EnhancedVolcano)
library(ggpubr)
library(plotly)
library(htmlwidgets)
library(igraph)
library(scales)
library(msigdbr)
library(future)
library(future.callr)
library(ggupset)
library(ggridges)
library(DESeq2)
library(dendextend)
library(SeuratDisk)
library(ggbeeswarm)
library(pals)
library(clustifyr)
library(speckle)
library(ggraph)
library(org.Hs.eg.db)
library(plyranges)

msig_h <- msigdbr(species = "Homo sapiens", category = "H") %>%
  dplyr::select(gs_name, entrez_gene) %>%
  dplyr::rename(ont = gs_name, gene = entrez_gene)
