## library() calls go here
library(targets)
library(crew)
library(crew.cluster)
library(numbatHelpers)
library(future)
library(seuratTools)
library(dotenv)
library(tarchetypes)
library('tidyverse')
library('fs')
library('readxl')
library(numbat)
library(Seurat)
library(patchwork)
library(msigdbr)
library(glue)
library(ggplotify)
library(rlang)
library(clusterProfiler)
library(DOSE)
library(writexl)
library(magick)
library(EnhancedVolcano)
library(ggpubr)
library(plotly)
library(htmlwidgets)
library(igraph)
library(scales)
library(msigdbr)
library(ggupset)
library(ggridges)
library(DESeq2)
library(dendextend)
library(SeuratDisk)
library(ggbeeswarm)
library(pals)
library(clustifyr)
library(speckle)
library(ggraph)
library(org.Hs.eg.db)
library(plyranges)
# Lazy-load annotation databases to save memory (~200 MB):
# library(org.Hs.eg.db)
# library(TxDb.Hsapiens.UCSC.hg38.knownGene)
# library(AnnotationHub)
# These are only used in enrichment/plot functions and are already
# referenced with :: namespace qualification where needed.
library(TCGAgistic)
library(maftools)
library(janitor)
library(plotgardener)
library(conflicted)
conflicts_prefer(dplyr::desc)
conflicts_prefer(seuratTools::find_all_markers)
conflicts_prefer(dplyr::n_distinct)
conflicts_prefer(dplyr::n)
conflicts_prefer(base::c)
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::select)
conflicts_prefer(base::setdiff)
conflicts_prefer(rlang::exprs)
# library(plotgardener)

msig_h <- msigdbr(species = "Homo sapiens", collection = "H") %>%
  dplyr::select(gs_name, ncbi_gene) %>%
  dplyr::rename(ont = gs_name, gene = ncbi_gene)

