SRR13884242:
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "1b"
- clone_opt %in% c(2,3,4) & p_cnv <= 0.5 & seg == "1b"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "16b"
- clone_opt %in% c(2,3,4) & p_cnv <= 0.5 & seg == "16b"
SRX10264520:
- clone_opt %in% c(2,3) & p_cnv <= 0.5 & seg == "16b"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "16b"
- clone_opt %in% c(2,3) & p_cnv <= 0.5 & seg == "1b"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "1b"
SRX10264521:
- clone_opt %in% c(2,3,4,5) & p_cnv <= 0.5 & seg == "1b"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "1b"
- clone_opt %in% c(2,3,4,5) & p_cnv <= 0.5 & seg == "16a"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "16a"
SRX10264522:
- clone_opt %in% c(2,3) & p_cnv <= 0.5 & seg == "1b"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "1b"
- clone_opt %in% c(2,3) & p_cnv <= 0.5 & seg == "16b"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "16b"
SRX10264523:
- clone_opt %in% c(2,3,4,5,6) & p_cnv <= 0.5 & seg == "1b"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "1b"
- clone_opt %in% c(5,6) & p_cnv <= 0.5 & seg == "2b"
- clone_opt %in% c(1,2,3,4) & p_cnv > 0.5 & seg == "2b"
SRX10264524:
- clone_opt %in% c(2,3,4,5,6) & p_cnv <= 0.5 & seg == "6c"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "6c"
- clone_opt %in% c(1,2,3,4,5) & p_cnv > 0.5 & seg == "2b"
- clone_opt %in% c(6) & p_cnv <= 0.5 & seg == "2b"
SRX10264525:
- clone_opt %in% c(3) & p_cnv <= 0.5 & seg == "2b"
- clone_opt %in% c(1,2) & p_cnv > 0.5 & seg == "2b"
- clone_opt %in% c(2) & p_cnv <= 0.5 & seg == "6a"
SRX10264526:
- clone_opt %in% c(2,3) & p_cnv <= 0.5 & seg == "1b"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "1b"
- clone_opt %in% c(1,2) & p_cnv > 0.5 & seg == "2a"
- clone_opt %in% c(3) & p_cnv <= 0.5 & seg == "2a"
SRX11133594:
- clone_opt %in% c(3) & p_cnv <= 0.5 & seg == "1b"
- clone_opt %in% c(1,2) & p_cnv > 0.5 & seg == "1b"
- clone_opt %in% c(2,3) & p_cnv <= 0.5 & seg == "16c"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "16c"
SRX11133593:
- clone_opt %in% c(2,3) & p_cnv <= 0.5 & seg == "16b"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "16b"
- clone_opt %in% c(3) & p_cnv <= 0.5 & seg == "1b"
- clone_opt %in% c(1,2) & p_cnv > 0.5 & seg == "1b"
SRX11133592:
- clone_opt %in% c(3,4) & p_cnv <= 0.5 & seg == "1b"
- clone_opt %in% c(1,2) & p_cnv > 0.5 & seg == "1b"
- clone_opt %in% c(2,3,4) & p_cnv <= 0.5 & seg == "16b"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "16b"
SRX11133588:
- clone_opt %in% c(3) & p_cnv <= 0.5 & seg == "1d"
- clone_opt %in% c(1,2) & p_cnv > 0.5 & seg == "1d"
- clone_opt %in% c(3) & p_cnv <= 0.5 & seg == "1e"
- clone_opt %in% c(1,2) & p_cnv > 0.5 & seg == "1e"
- clone_opt %in% c(1,3) & p_cnv > 0.5 & seg == "6b"
- clone_opt %in% c(2) & p_cnv <= 0.5 & seg == "6b"
- clone_opt %in% c(1,3) & p_cnv > 0.5 & seg == "16e"
- clone_opt %in% c(2) & p_cnv <= 0.5 & seg == "16e"
SRX11133587:
- clone_opt %in% c(2,3,4,5,6,7) & p_cnv <= 0.5 & seg == "1f"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "1f"
- clone_opt %in% c(2,3,4,5,6,7) & p_cnv <= 0.5 & seg == "2a"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "2a"
- clone_opt %in% c(2,3,4,5,6,7) & p_cnv <= 0.5 & seg == "6a"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "6a"
- clone_opt %in% c(3,4) & p_cnv <= 0.5 & seg == "16d"
- clone_opt %in% c(1,2,5,6,7) & p_cnv > 0.5 & seg == "16d"
SRX11133585:
- clone_opt %in% c(3) & p_cnv <= 0.5 & seg == "1c"
- clone_opt %in% c(1,2) & p_cnv > 0.5 & seg == "1c"
- clone_opt %in% c(1,2,4) & p_cnv > 0.5 & seg == "16c"
- clone_opt %in% c(3) & p_cnv <= 0.5 & seg == "16c"
SRX14116947:
- clone_opt %in% c(2,3) & p_cnv <= 0.5 & seg == "1b"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "1b"
SRX14116944:
- clone_opt %in% c(2,3,4,5) & p_cnv <= 0.5 & seg == "1c"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "1c"
- clone_opt %in% c(4,5) & p_cnv <= 0.5 & seg == "2a"
- clone_opt %in% c(1,2,3) & p_cnv > 0.5 & seg == "2a"
- clone_opt %in% c(1,2) & p_cnv > 0.5 & seg == "6a"
- clone_opt %in% c(3,4,5) & p_cnv <= 0.5 & seg == "6a"
SRX22868105:
- clone_opt %in% c(2,3,4) & p_cnv <= 0.5 & seg == "6b"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "6b"
- clone_opt %in% c(1,2,3) & p_cnv > 0.5 & seg == "16e"
- clone_opt %in% c(4) & p_cnv <= 0.5 & seg == "16e"
SRX22868104:
- clone_opt %in% c(2,3) & p_cnv <= 0.5 & seg == "1d"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "1d"
- clone_opt %in% c(2,3) & p_cnv <= 0.5 & seg == "6c"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "6c"
SRX22868103:
- clone_opt %in% c(2,3,4,5) & p_cnv <= 0.5 & seg == "1c"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "1c"
- clone_opt %in% c(4,5) & p_cnv <= 0.5 & seg == "2a"
- clone_opt %in% c(1,2,3) & p_cnv > 0.5 & seg == "2a"
- clone_opt %in% c(1,2) & p_cnv > 0.5 & seg == "6a"
- clone_opt %in% c(3,4,5) & p_cnv <= 0.5 & seg == "6a"
SRX22868102:
- clone_opt %in% c(2,3,4) & p_cnv <= 0.5 & seg == "1k"
- clone_opt %in% c(1) & p_cnv > 0.5 & seg == "1k"
- clone_opt %in% c(1,2,3) & p_cnv > 0.5 & seg == "16a"
- clone_opt %in% c(4) & p_cnv <= 0.5 & seg == "16a"
SRX10031194: []
SRX10264517: []
SRX10264518: []
SRX10264519: []
SRX11133589: []
SRX14116945: []
SRX14116946: []
SRX14116948: []
