# Figures and tables targets: aggregate output target, study metadata,
# supplemental figures/tables, marker plots, cluster analyses, clone trees,
# large numbat plots, sample-specific integration figures, and pipeline notification.
# Defines: pipeline_targets_figures (spliced into tar_plan in _targets.R)

pipeline_targets_figures <- c(

list(
  # --- aggregate output tracking ---

  tar_target(
    figures_and_tables,
    list(
      cluster_comparisons_by_phase_for_disctinct_clones = cluster_comparisons_by_phase_for_disctinct_clones,
      clustree_compilation = clustree_compilation,
      collage_compilation = collage_compilation,
      fig_04 = fig_04,     # integrated 1q fig for all 1q+ samples
      fig_04_v2 = fig_04_v2, # updated integrated 1q fig for all 1q+ samples
      fig_03 = fig_03,     # integrated 16q- alternative resolutions
      fig_04_09 = fig_04_09,     # 2p+ integrated analysis
      fig_04_07 = fig_04_07,  # fig 04-07 combined
      fig_05 = fig_05,     # 6p+ integrated analysis
      fig_07a = fig_07a,    # 1q+ cluster diffex after integration
      fig_07b = fig_07b,    # 1q+ cluster diffex without integration
      fig_08a = fig_08a,    # 16q- cluster diffex after integration
      fig_08b = fig_08b,    # 16q- cluster diffex without integration
      fig_09 = fig_09,     # 2p+ corresponding cluster analysis
      fig_10 = fig_10,     # 6p+ corresponding cluster analysis
      # fig s01 generated by hand in Inkscape from Kooi et al.
      fig_03_05 = fig_03_05,        # regression diagnostics
      fig_s02_table_s04 = fig_s02_table_s04, # tcga frequency
      fig_s03 = fig_s03,    # gistic plots
      fig_s03a = fig_s03a,   # unfiltered numbat heatmaps
      fig_s04 = fig_s04,    # study cell stats
      fig_s04_08 = fig_s04_08, # 2p+ sample-specific analyses after integration
      fig_s04_09 = fig_s04_09, # 2p+ sample-specific analyses without integration
      fig_s05 = fig_s05,    # smoothed expression
      fig_s06a = fig_s06a,   # karyograms
      fig_s07 = fig_s07,    # 1q+ sample-specific analyses after integration
      fig_s08 = fig_s08,    # 1q+ clone diffex within clusters
      fig_s09 = fig_s09,    # 1q+ cluster diffex of interest
      fig_s10 = fig_s10,    # 16q- clone diffex within clusters
      fig_s12 = fig_s12,    # 16q- sample-specific analyses after integration
      fig_s13 = fig_s13,    # filtered numbat heatmaps
      fig_s20 = fig_s20,    # 2p+ clone diffex within clusters
      fig_s23 = fig_s23,    # 6p+ sample-specific analyses after integration
      fig_s25 = fig_s25,    # subtype markers
      clone_trees_segments = clone_trees_segments_files, # clone trees annotated by raw NUMBAT segments (GT_opt)
      # oncoprint_enrich_clones_plots_gobp,
      # oncoprint_enrich_clusters_plots_gobp,
      oncoprint_plots = oncoprint_plots,
      table_06 = table_06,               # rod-rich samples
      table_all_diffex_clones = table_all_diffex_clones, # diffex between clones per cluster
      table_s01 = table_s01, # umi, genes detected, mito %
      table_s02 = table_s02, # detailed sample metadata
      table_s03 = table_s03, # clusters removed with marker genes
      table_s07 = table_s07, # 1q+ clone percentage per cluster
      table_s09 = table_s09, # 16q- clone percentage per cluster
      table_s10 = table_s10  # 2p+ clone percentage per cluster
    )
  ),

  # --- study metadata and overview figures ---

  # Collect per-sample cell count and QC statistics across all studies.
  tar_target(study_cell_stats, collect_study_metadata()),

  # Cell cycle space and clone distribution plots for figure 01.
  tar_target(fig_01, plot_fig_01(final_seus[["SRR14800534"]])),

  # Plot study-level metadata summary for supplemental figure S04.
  tar_target(fig_s04, plot_study_metadata(study_cell_stats)),

  tar_target(table_s01, make_table_s01(study_cell_stats)), # umi, genes detected, mito %
  tar_target(table_s02, make_table_s02()), # detailed sample metadata
  tar_target(table_s03, make_table_s03(cluster_dictionary)), # tally clusters removed with marker genes

  # RB SCNA frequency in TCGA by cancer type (Taylor et al. 2018).
  tar_target(fig_s02_table_s04, rb_scna_frequency_in_tcga_by_cancer_type()),
  tar_target(fig_s03, plot_tcga_gistic()),

  tar_target(table_s07, make_table_s07()), # For each 1q+ sample, percentage of clone in cluster.
  tar_target(table_s09, make_table_s09(seu_path = "output/seurat/integrated_16q/integrated_seu_16q_complete.rds", table_path = "results/table_s09.csv")),
  tar_target(table_s10, make_table_s10(seu_path = "output/seurat/integrated_2p/seurat_2p_integrated_duo.rds", table_path = "results/table_s10.csv")),

  # --- subtype and marker plots ---

  # Score each sample for subtype signatures and generate violin plots per sample.
  tar_target(subtype_violins,
    score_and_vlnplot_seu(final_seus, numbat_rds_files, large_clone_simplifications, subtype_markers),
    pattern = map(final_seus),
    iteration = "list"
  ),

  # Combine all per-sample subtype violin PDFs into a single merged PDF.
  tar_target(
    subtype_violin_files,
    qpdf::pdf_combine(unlist(subtype_violins), "results/scna_vlns.pdf")
  ),

  # Plot cell cycle phase distribution across all samples grouped by SCNA type.
  tar_target(
    patchwork_phase_plot,
    plot_phase_distribution_of_all_samples_by_scna(final_seus)
  ),

  # Score cells for cancer meta-program signatures and plot per-sample heatmaps.
  tar_target(mp_heatmaps,
    score_and_heatmap_seu(final_seus, mps[["Cancer"]], leiden_cluster_file = "results/adata_filtered_metadata_0.2.csv"),
    pattern = map(final_seus),
    iteration = "list"
  ),

  # Plot violin plots of interesting genes across samples grouped by SCNA clone.
  tar_target(
    marker_gene_vlnplots_by_clone,
    plot_putative_marker_across_samples(unlist(interesting_genes), scna_seus, plot_type = VlnPlot, group_by = "scna")
  ),

  # Plot violin plots of interesting genes across all SCNA samples grouped by cluster.
  tar_target(
    cluster_vlns_all,
    plot_putative_marker_across_samples(unlist(interesting_genes), scna_seus, plot_type = VlnPlot, group_by = "clusters")
  )
), # end list block before first tar_map

# cluster_vlns_1q / _2p / _6p / _16q — generated via tar_map over scna_map_values
tarchetypes::tar_map(
  values = scna_map_values[, c("scna", "seus_sym")],
  names  = "scna",
  tar_target(cluster_vlns,
    plot_putative_marker_across_samples(
      interesting_genes[[scna]], seus_sym,
      plot_type = VlnPlot, group_by = "clusters", extension = scna
    )
  )
),

list(
  tar_target(
    cluster_vlns_s2,
    plot_putative_marker_across_samples(interesting_genes[["S2"]], scna_seus, plot_type = VlnPlot, group_by = "clusters", extension = "s2")
  ),

  tar_target(
    cluster_vlns_s1,
    plot_putative_marker_across_samples(interesting_genes[["S1"]], scna_seus, plot_type = VlnPlot, group_by = "clusters", extension = "s1")
  )
), # end list block before second tar_map

# factor_heatmaps_{scna} + factor_heatmaps_combined_{scna} via tar_map
tarchetypes::tar_map(
  values = scna_map_values[, c("scna", "seus_sym")],
  names  = "scna",
  tar_target(factor_heatmaps,
    plot_seu_gene_heatmap(seus_sym, large_clone_comparisons, scna_of_interest = scna, w = 8, h = 12),
    pattern   = map(seus_sym),
    iteration = "list"
  ),
  tar_target(factor_heatmaps_combined,
    qpdf::pdf_combine(factor_heatmaps, paste0("results/factor_heatmaps_", scna, ".pdf"))
  )
),

list(
  # Combine all four SCNA factor heatmap PDFs into the fig_s16 supplemental PDF.
  tar_target(all_factor_heatmaps,
    qpdf::pdf_combine(
      c(factor_heatmaps_combined_1q, factor_heatmaps_combined_2p,
        factor_heatmaps_combined_6p, factor_heatmaps_combined_16q),
      "results/fig_s16.pdf"
    )
  ),

  # Plot feature plots of interesting genes across samples grouped by cluster.
  tar_target(
    marker_gene_featureplots_by_cluster,
    plot_putative_marker_across_samples(unlist(interesting_genes), scna_seus, plot_type = FeaturePlot, group_by = "clusters")
  ),

  # --- cluster markers ---

  tar_target(
    cluster_markers,
    collect_all_markers(numbat_rds_files, "results/clusters.xlsx")
  ),

  tar_target(
    large_clusters,
    collect_clusters_from_seus(final_seus)
  ),

  # --- cluster comparisons ---

  tar_target(cluster_comparisons_by_phase_for_disctinct_clones,
    make_cluster_comparisons_by_phase_for_disctinct_clones(cluster_comparisons, overall_seus),
    pattern = map(cluster_comparisons),
    iteration = "list"
  ),

  # --- large numbat plots ---

  tar_target(large_numbat_pdfs,
    convert_numbat_pngs(numbat_rds_files),
    pattern = map(numbat_rds_files),
    iteration = "list"
  ),

  tar_target(
    large_numbat_expression,
    retrieve_numbat_plot_type(large_numbat_pdfs, "exp_roll_clust.pdf")
  ),

  tar_target(
      large_numbat_bulk_clones,
      retrieve_numbat_plot_type(large_numbat_pdfs, "bulk_clones_final.pdf")
  ),

  tar_target(fig_s05,
    qpdf::pdf_combine(large_numbat_expression, "results/numbat_expression.pdf")
  ),

  # --- filtered numbat plots ---

  tar_target(filtered_numbat_pdfs,
    convert_numbat_pngs(numbat_rds_filtered_files),
    pattern = map(numbat_rds_filtered_files),
    iteration = "list"
  ),

  tar_target(
    filtered_numbat_expression,
    retrieve_numbat_plot_type(filtered_numbat_pdfs, "exp_roll_clust.pdf")
  ),

  tar_target(
    filtered_numbat_bulk_clones,
    retrieve_numbat_plot_type(filtered_numbat_pdfs, "bulk_clones_final.pdf")
  ),

  # For each sample, prefer the filtered bulk clones plot when available,
  # falling back to the unfiltered one. This ensures consistency with
  # fig_s03a_plots, which also prefers the filtered numbat run.
  tar_target(
    preferred_numbat_bulk_clones,
    {
      filt_ids <- str_extract(filtered_numbat_bulk_clones, "SRR[0-9]*")
      purrr::map_chr(large_numbat_bulk_clones, function(path) {
        sid <- str_extract(path, "SRR[0-9]*")
        filt_match <- filtered_numbat_bulk_clones[filt_ids == sid]
        if (length(filt_match) > 0) filt_match[[1]] else path
      })
    }
  ),

  tar_target(nb_paths_s06a,
    dir_ls("output/numbat_sridhar/", regexp = ".*SRR[0-9]*_numbat.rds", recurse = TRUE) |> sort()
  ),

  tar_target(ideogram_res_s06a_unfiltered,
    make_rb_scna_ideograms(nb_paths_s06a),
    pattern = map(nb_paths_s06a)
  ),

  tar_target(nb_paths_s06a_filtered,
    dir_ls("output/numbat_sridhar_filtered/", regexp = ".*SRR[0-9]*_numbat.rds", recurse = TRUE) |> sort()
  ),

  tar_target(ideogram_res_s06a_filtered,
    make_rb_scna_ideograms(nb_paths_s06a_filtered, suffix = "_filtered"),
    pattern = map(nb_paths_s06a_filtered)
  ),

  tar_target(fig_s06a,
    {
      # targets flattens named list branch results: odd = plot paths, even = tables
      odd_idx <- seq(1, length(ideogram_res_s06a_unfiltered), by = 2)
      plot_paths <- as.character(ideogram_res_s06a_unfiltered[odd_idx])
      tables <- ideogram_res_s06a_unfiltered[odd_idx + 1] |>
        set_names(str_extract(plot_paths, "SRR[0-9]*"))
      writexl::write_xlsx(tables, "results/table_s12.xlsx")
      qpdf::pdf_combine(plot_paths, "results/fig_s06a.pdf")
      list("results/fig_s06a.pdf", "results/table_s12.xlsx")
    }
  ),

  tar_target(clone_trees_old,
    retrieve_numbat_plot_type(filtered_large_plot_files, "tree_filtered.pdf")
  ),

  tar_target(large_numbat_heatmap_files,
    retrieve_numbat_plot_type(large_numbat_pdfs, "panel_2.pdf")
  ),

  tar_target(large_numbat_heatmap_pdf,
    qpdf::pdf_combine(large_numbat_heatmap_files, "results/large_numbat_heatmaps.pdf")
  ),

  tar_target(large_numbat_sample_pdfs,
    reroute_done_to_results_pdf(numbat_rds_files, "_large"),
    pattern = map(numbat_rds_files),
    iteration = "list"
  ),

  tar_target(
    filtering_timelines,
    qpdf::pdf_combine(dir_ls("results", regexp = ".*SRR[0-9]*_filtering_timeline.pdf"), "results/filtering_timelines.pdf")
  ),

  # --- clone distribution and pearls ---

  tar_target(paired_clone_distribution_plots,
    calculate_clone_distribution(scna_seus, cluster_orders, pairwise = TRUE),
    iteration = "list"
  )
), # end list block before third tar_map

# clone_pearls_1q/2p/6p/16q — generated via tar_map over scna_map_values
# var_y: 1q and 16q use "phase_level"; 2p and 6p use "clusters"
tarchetypes::tar_map(
  values = scna_map_values,
  names  = "scna",
  tar_target(clone_pearls,
    { force(cluster_orders_sqlite); plot_clone_pearls(seus_sym, var_y = var_y) },
    pattern   = map(seus_sym),
    iteration = "list"
  )
),

list(
  tar_target(cluster_terms,
    enrich_by_cluster(scna_seus),
    pattern   = map(scna_seus),
    iteration = "list"
  ),

  tar_target(unpaired_clone_distribution_plots,
    calculate_clone_distribution(final_seus, cluster_orders, large_clone_comparisons = large_clone_comparisons, pairwise = FALSE),
    pattern = map(final_seus),
    iteration = "list"
  ),

  tar_target(
    cluster_scorecard,
    score_clusters_up_down(paired_clone_distribution_plots)
  ),

  tar_target(clusters_and_markers,
    plot_seu_clusters_and_markers(debranched_seus, cluster_orders),
    pattern = map(debranched_seus),
    iteration = "list"
  ),

  # --- clone trees ---

  tar_target(debranched_clone_tree_files,
    save_clone_tree_from_path(debranched_seus, numbat_rds_files, large_clone_simplifications, label = "_debranched_clone_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(debranched_seus),
    iteration = "list"
  ),

  tar_target(debranched_clone_trees,
    plot_clone_tree_from_path(debranched_seus, numbat_rds_files, large_clone_simplifications, label = "_debranched_clone_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(debranched_seus),
    iteration = "list"
  ),

  tar_target(
    debranched_clone_trees_file,
    qpdf::pdf_combine(debranched_clone_tree_files, "results/debranched_clone_trees.pdf")
  ),


  tar_target(unfiltered_clone_tree_files,
    save_clone_tree_from_path(unfiltered_seus, numbat_rds_files, large_clone_simplifications, label = "_unfiltered_clone_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(unfiltered_seus),
    iteration = "list"
  ),

  tar_target(filtered_clone_tree_files,
    save_clone_tree_from_path(filtered_seus, numbat_rds_files, large_clone_simplifications, label = "_filtered_clone_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(filtered_seus),
    iteration = "list"
  ),

  # Clone trees with raw NUMBAT segment labels (no SCNA simplification applied).
  tar_target(filtered_clone_trees_segments_files,
    save_clone_tree_from_path(filtered_seus, numbat_rds_files, NULL, label = "_filtered_segment_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(filtered_seus),
    iteration = "list"
  ),

  # Clone trees with raw NUMBAT segment labels (no SCNA simplification applied).
  tar_target(unfiltered_clone_trees_segments_files,
    save_clone_tree_from_path(unfiltered_seus, numbat_rds_files, NULL, label = "_unfiltered_segment_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(unfiltered_seus),
    iteration = "list"
  ),

  tar_target(final_clone_tree_files,
    save_clone_tree_from_path(final_seus, numbat_rds_files, large_clone_simplifications, label = "_clone_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(final_seus),
    iteration = "list"
  ),

  tar_target(
    final_clone_trees_file,
    qpdf::pdf_combine(final_clone_tree_files, "results/final_clone_trees.pdf")
  ),

  # --- sample-specific integration figures ---

  # integrated 1q fig for all 1q+ samples (thesis fig 4.3)
  tar_target(fig_04,
    { force(cluster_orders_sqlite); plot_integrated_1q_fig(cluster_orders) }
  ),

  tar_target(fig_04_v2,
    { force(cluster_orders_sqlite); plot_fig_04_afterall(cluster_orders) }
  ),

  # Sample-specific analyses of tumors with 1q+ subclones after integration.
  tar_target(fig_s07,
    { force(cluster_orders_sqlite); sample_specific_analyses_of_tumors_with_scna_subclones_after_integration(integrated_seus_1q, cluster_orders, "results/fig_s07.pdf") }
  ),

  # Sample-specific analyses of tumors with 16q- subclones after integration.
  tar_target(fig_s12,
    { force(cluster_orders_sqlite); sample_specific_analyses_of_tumors_with_scna_subclones_after_integration(integrated_seus_16q, cluster_orders, "results/fig_s12.pdf") }
  ),

  # Sample-specific analyses of tumors with 2p+ subclones after integration.
  tar_target(fig_s04_08,
    { force(cluster_orders_sqlite); sample_specific_analyses_of_tumors_with_scna_subclones_after_integration(integrated_seus_2p, cluster_orders, "results/fig_s04_08.pdf") }
  ),

  tar_target(fig_s23,
    { force(cluster_orders_sqlite); sample_specific_analyses_of_tumors_with_scna_subclones_after_integration(integrated_seus_6p, cluster_orders, "results/fig_s23.pdf") }
  ),

  tar_target(fig_s25,
    plot_fig_s25(subtype_markers = subtype_markers)
  ),

  # Alternative resolutions for integrated 16q- analysis
  tar_target(fig_03,
    plot_fig_03(cluster_orders)
  ),

  tar_target(fig_04_07,
    plot_fig_04_07(cluster_orders)
  ),

  tar_target(fig_04_09,
    plot_fig_04_05(
      c("output/seurat/integrated_2p/seurat_2p_integrated_duo.rds",
        "output/seurat/SRR13884247_branch_6_filtered_seu.rds"),
      corresponding_clusters_enrichments[[6]],
      plot_path = "results/fig_04_09.pdf",
      integrated_seu_paths = integrated_seus_2p,
      cluster_order = cluster_orders,
      large_clone_comparisons = large_clone_comparisons,
      scna_of_interest = "2p", width = 14, height = 10
    )
  ),

  tar_target(fig_05,
    plot_fig_04_05(
      "output/seurat/integrated_6p/integrated_seu_6p_duo.rds",
      corresponding_clusters_enrichments[[7]],
      integrated_seu_paths = integrated_seus_6p,
      plot_path = "results/fig_05.pdf",
      cluster_order = cluster_orders,
      large_clone_comparisons = large_clone_comparisons,
      scna_of_interest = "6p", width = 18, height = 10
    )
  ),

  tar_target(fig_s08,  # Differential expression between integrated 1q clones within clusters
    plot_fig_s08()
  ),

  tar_target(fig_s09,  # 1q+ cluster diffex of interest
    plot_fig_s09()
  ),

  tar_target(fig_s10,  # Differential expression between integrated 16q clones within clusters
    plot_fig_s10()
  ),

  tar_target(fig_s20,  # Differential expression between integrated 2p clones within clusters
    plot_fig_s20()
  ),

  # --- per-sample summary collation ---

  tar_target(sample_summaries,
    collate_sample_summary(
      ideogram_res_s06a_unfiltered,
      ideogram_res_s06a_filtered,
      unfiltered_clone_tree_files,
      unfiltered_clone_trees_segments_files,
      filtered_clone_tree_files,
      filtered_clone_trees_segments_files,
      fig_s03a_unfiltered_plots,
      fig_s03a_plots,
      large_numbat_expression,
      filtered_numbat_expression,
      preferred_numbat_bulk_clones,
      filtered_numbat_bulk_clones
    ),
    pattern = map(unfiltered_clone_tree_files),
    iteration = "list"
  ),

  # --- pipeline notification ---

  tar_target(
    pipeline_notification,
    {
      # depend on figures_and_tables so this runs after the main outputs are ready
      invisible(figures_and_tables)
      tryCatch({
        send_pipeline_notification(subject = "Targets pipeline completed", body = NULL)
        TRUE
      }, error = function(e) {
        warning("Failed to send pipeline notification: ", e$message)
        FALSE
      })
    }
  )

)) # end list + end c()
