# Figures and tables targets: aggregate output target, study metadata,
# supplemental figures/tables, marker plots, cluster analyses, clone trees,
# large numbat plots, sample-specific integration figures, and pipeline notification.
# Defines: pipeline_targets_figures (spliced into tar_plan in _targets.R)

# Crew controller resource assignments for targets
.light_resources <- tar_resources(crew = tar_resources_crew(controller = "light"))
.heavy_resources <- tar_resources(crew = tar_resources_crew(controller = "heavy"))

pipeline_targets_figures <- c(

list(
  # --- aggregate output tracking ---

  tar_target(figures_and_tables, {
    items <- list(
      cluster_comparisons_by_phase_for_disctinct_clones = cluster_comparisons_by_phase_for_disctinct_clones,
      clustree_compilation = clustree_compilation,
      collage_compilation = collage_compilation,
      fig_single_sample_panels              = fig_single_sample_panels,
      fig_single_sample_panels_with_diploid = fig_single_sample_panels_with_diploid,
      fig_1q_integrated                     = fig_1q_integrated,
      fig_1q_integrated_v2                  = fig_1q_integrated_v2,
      fig_16q_integrated                    = fig_16q_integrated,
      fig_2p_integrated                     = fig_2p_integrated,
      fig_1q_16q_combined                   = fig_1q_16q_combined,
      fig_6p_integrated                     = fig_6p_integrated,
      fig_1q_cluster_diffex_integrated      = fig_1q_cluster_diffex_integrated,
      fig_1q_cluster_diffex_unintegrated    = fig_1q_cluster_diffex_unintegrated,
      fig_16q_cluster_diffex_integrated     = fig_16q_cluster_diffex_integrated,
      fig_16q_cluster_diffex_unintegrated   = fig_16q_cluster_diffex_unintegrated,
      fig_2p_corresponding_clusters         = fig_2p_corresponding_clusters,
      fig_6p_corresponding_clusters         = fig_6p_corresponding_clusters,
      # fig s01 generated by hand in Inkscape from Kooi et al.
      fig_regression_diagnostics            = fig_regression_diagnostics,
      fig_tcga_scna_frequency               = fig_tcga_scna_frequency,
      fig_tcga_gistic                       = fig_tcga_gistic,
      fig_numbat_heatmaps                   = fig_numbat_heatmaps,
      fig_study_cell_stats                  = fig_study_cell_stats,
      fig_2p_sample_specific_integrated     = fig_2p_sample_specific_integrated,
      fig_2p_sample_specific_unintegrated   = fig_2p_sample_specific_unintegrated,
      fig_numbat_expression_smoothed        = fig_numbat_expression_smoothed,
      fig_karyograms                        = fig_karyograms,
      fig_1q_sample_specific_integrated     = fig_1q_sample_specific_integrated,
      fig_1q_clone_diffex_within_clusters   = fig_1q_clone_diffex_within_clusters,
      fig_1q_cluster_diffex_of_interest     = fig_1q_cluster_diffex_of_interest,
      fig_16q_clone_diffex_within_clusters  = fig_16q_clone_diffex_within_clusters,
      fig_16q_sample_specific_integrated    = fig_16q_sample_specific_integrated,
      fig_numbat_heatmaps_permissive        = fig_numbat_heatmaps_permissive,
      fig_2p_clone_diffex_within_clusters   = fig_2p_clone_diffex_within_clusters,
      fig_6p_sample_specific_integrated     = fig_6p_sample_specific_integrated,
      fig_subtype_markers                   = fig_subtype_markers,
      clone_trees_segments = filtered_clone_trees_segments_files,
      clone_tree_collage = clone_tree_collage,
      clone_tree_collage_of_merged_replicates = clone_tree_collage_of_merged_replicates,
      # oncoprint_enrich_clones_plots_gobp,
      # oncoprint_enrich_clusters_plots_gobp,
      oncoprint_plots = oncoprint_plots,
      table_rod_rich_samples  = table_rod_rich_samples_csv,
      table_all_diffex_clones = table_all_diffex_clones,
      table_qc_stats          = table_qc_stats,
      table_sample_metadata   = table_sample_metadata,
      table_removed_clusters  = table_removed_clusters,
      table_1q_clone_per_cluster  = table_1q_clone_per_cluster,
      table_16q_clone_per_cluster = table_16q_clone_per_cluster,
      table_2p_clone_per_cluster  = table_2p_clone_per_cluster,
      sample_summaries = sample_summaries,
      cell_counts_table = filtering_cell_counts_table
    )

    # Build manifest: one row per file, annotated with document label from figure_order.
    # Items not in figure_order get NA in document_label.
    manifest_df <- purrr::imap(items, function(val, name) {
      label <- figure_order[name]
      paths <- unlist(val)
      paths <- paths[!is.na(paths) & nchar(paths) > 0]
      data.frame(
        document_label = if (length(label) == 0 || is.na(label)) NA_character_ else unname(label),
        semantic_name  = name,
        file_path      = if (length(paths) == 0) NA_character_ else paths,
        stringsAsFactors = FALSE
      )
    }) |>
      dplyr::bind_rows() |>
      dplyr::arrange(document_label)

    manifest_path <- "results/figures_and_tables_manifest.csv"
    readr::write_csv(manifest_df, manifest_path)

    c(items, list(manifest = manifest_path))
  }),

  # --- study metadata and overview figures ---

  # Collect per-sample cell count and QC statistics across all studies.
  # Returns file path (simple string, trivially serializable)
  tar_target(study_cell_stats, collect_study_metadata()),

  # Cell cycle space and clone distribution plots for figure 01.
  tar_target(fig_01, plot_fig_01(unlist(seus_low_hypoxia)[grepl("SRX11133594", unlist(seus_low_hypoxia))])),

  # Static external figures tracked as file targets.
  # clone_tree_collage.png is cited as both Fig. 1b (main text) and Fig. S24 (supplement).
  tar_target(clone_tree_collage,
    "doc/external_figures_and_tables/clone_tree_collage.png",
    format = "file"
  ),

  # clone_tree_collage_of_merged_replicates.png must be created before this target can run.
  tar_target(clone_tree_collage_of_merged_replicates,
    "doc/external_figures_and_tables/clone_tree_collage_of_merged_replicates.png",
    format = "file"
  ),

  tar_target(single_sample_panel_ids,
    c("SRX22868105", "SRX22868103", "SRX22868102", "SRX10264522",
      "SRX10264523", "SRX10264526", "SRX11133594", "SRX11133593", "SRX11133592")
  ),

  # Multi-panel single-sample figure: Numbat heatmap, clone tree, UMAPs, CC space, clone distribution.
  tar_target(fig_single_sample_panels,
    plot_fig_02(
      unlist(seus_low_hypoxia)[grepl(single_sample_panel_ids, unlist(seus_low_hypoxia))],
      numbat_rds_files,
      large_clone_simplifications
    ),
    pattern = map(single_sample_panel_ids),
    iteration = "list"
  ),

  tar_target(fig_single_sample_panels_high_hypoxia,
    plot_fig_02(
      unlist(seus_high_hypoxia)[grepl(single_sample_panel_ids, unlist(seus_high_hypoxia))],
      numbat_rds_files,
      large_clone_simplifications
    ),
    pattern = map(single_sample_panel_ids),
    iteration = "list"
  ),

  tar_target(low_hypoxia_diploid_merged_seu,
    merge_hypoxia_with_diploid(
      unlist(seus_low_hypoxia)[grepl(single_sample_panel_ids, unlist(seus_low_hypoxia))],
      diploid_seu,
      slug = "low_hypoxia"
    ),
    pattern = map(single_sample_panel_ids),
    iteration = "list",
    format = "file"
  ),

  tar_target(low_hypoxia_w_diploid_umap_plots,
    plot_diploid_seu_umaps(low_hypoxia_diploid_merged_seu, celltype_markers, use_integrated_clusters = TRUE),
    pattern = map(low_hypoxia_diploid_merged_seu),
    iteration = "list",
    format = "file"
  ),

  tar_target(fig_single_sample_panels_with_diploid,
    plot_fig_02(
      low_hypoxia_diploid_merged_seu,
      numbat_rds_files,
      large_clone_simplifications
    ),
    pattern = map(low_hypoxia_diploid_merged_seu),
    iteration = "list"
  ),

  tar_target(high_hypoxia_diploid_merged_seu,
    merge_hypoxia_with_diploid(
      unlist(seus_high_hypoxia)[grepl(single_sample_panel_ids, unlist(seus_high_hypoxia))],
      diploid_seu,
      slug = "high_hypoxia"
    ),
    pattern = map(single_sample_panel_ids),
    iteration = "list",
    format = "file"
  ),

  tar_target(high_hypoxia_w_diploid_umap_plots,
    plot_diploid_seu_umaps(high_hypoxia_diploid_merged_seu, celltype_markers, use_integrated_clusters = TRUE),
    pattern = map(high_hypoxia_diploid_merged_seu),
    iteration = "list",
    format = "file"
  ),

  # Plot study-level metadata summary.
  tar_target(fig_study_cell_stats, {
    study_cell_stats
    plot_study_metadata(readr::read_csv("results/study_cell_stats.csv", show_col_types = FALSE))
  }),

  tar_target(table_qc_stats, {
    study_cell_stats
    make_table_s01(readr::read_csv("results/study_cell_stats.csv", show_col_types = FALSE))
  }),
  tar_target(table_sample_metadata, make_table_s02()),
  tar_target(table_removed_clusters, make_table_s03(cluster_dictionary)),

  # RB SCNA frequency in TCGA by cancer type (Taylor et al. 2018).
  tar_target(fig_tcga_scna_frequency, rb_scna_frequency_in_tcga_by_cancer_type()),
  tar_target(fig_tcga_gistic, plot_tcga_gistic()),

  tar_target(table_1q_clone_per_cluster,  make_table_s07()),
  tar_target(table_16q_clone_per_cluster, make_table_s09(seu_path = "output/seurat/integrated_16q/integrated_seu_16q_complete.rds", table_path = "results/table_16q_clone_per_cluster.csv")),
  tar_target(table_2p_clone_per_cluster,  make_table_s10(seu_path = "output/seurat/integrated_2p/seurat_2p_integrated_duo.rds",    table_path = "results/table_2p_clone_per_cluster.csv")),

  # --- subtype and marker plots ---

  # Score each sample for subtype signatures and generate violin plots per sample.
  tar_target(subtype_violins,
    score_and_vlnplot_seu(final_seus, numbat_rds_files, large_clone_simplifications, subtype_markers),
    pattern = map(final_seus),
    iteration = "list"
  ),

  # Combine all per-sample subtype violin PDFs into a single merged PDF.
  tar_target(
    subtype_violin_files,
    {
      paths <- unlist(subtype_violins)
      paths <- paths[!is.na(paths)]
      qpdf::pdf_combine(paths, "results/scna_vlns.pdf")
    }
  ),

  # Plot cell cycle phase distribution across all samples grouped by SCNA type.
  tar_target(
    patchwork_phase_plot,
    plot_phase_distribution_of_all_samples_by_scna(final_seus)
  ),

  # Score cells for cancer meta-program signatures and plot per-sample heatmaps.
  tar_target(mp_heatmaps,
    score_and_heatmap_seu(final_seus, mps[["Cancer"]], leiden_cluster_file = "results/adata_filtered_metadata_0.2.csv"),
    pattern = map(final_seus),
    iteration = "list"
  ),

  # Plot violin plots of interesting genes across samples grouped by SCNA clone.
  tar_target(
    marker_gene_vlnplots_by_clone,
    plot_putative_marker_across_samples(unlist(interesting_genes), scna_seus, plot_type = VlnPlot, group_by = "scna")
  ),

  # Plot violin plots of interesting genes across all SCNA samples grouped by cluster.
  tar_target(
    cluster_vlns_all,
    plot_putative_marker_across_samples(unlist(interesting_genes), scna_seus, plot_type = VlnPlot, group_by = "clusters")
  )
), # end list block before first tar_map

# cluster_vlns_1q / _2p / _6p / _16q — generated via tar_map over scna_map_values
tarchetypes::tar_map(
  values = scna_map_values[, c("scna", "seus_sym")],
  names  = "scna",
  tar_target(cluster_vlns,
    plot_putative_marker_across_samples(
      interesting_genes[[scna]], seus_sym,
      plot_type = VlnPlot, group_by = "clusters", extension = scna
    )
  )
),

list(
  tar_target(
    cluster_vlns_s2,
    plot_putative_marker_across_samples(interesting_genes[["S2"]], scna_seus, plot_type = VlnPlot, group_by = "clusters", extension = "s2")
  ),

  tar_target(
    cluster_vlns_s1,
    plot_putative_marker_across_samples(interesting_genes[["S1"]], scna_seus, plot_type = VlnPlot, group_by = "clusters", extension = "s1")
  )
), # end list block before second tar_map

# factor_heatmaps_{scna} + factor_heatmaps_combined_{scna} via tar_map
tarchetypes::tar_map(
  values = scna_map_values[, c("scna", "seus_sym")],
  names  = "scna",
  tar_target(factor_heatmaps,
    plot_seu_gene_heatmap(seus_sym, large_clone_comparisons, scna_of_interest = scna, w = 8, h = 12),
    pattern   = map(seus_sym),
    iteration = "list"
  ),
  tar_target(factor_heatmaps_combined,
    qpdf::pdf_combine(factor_heatmaps, paste0("results/factor_heatmaps_", scna, ".pdf"))
  )
),

list(
  # Combine all four SCNA factor heatmap PDFs into the fig_s16 supplemental PDF.
  tar_target(all_factor_heatmaps,
    qpdf::pdf_combine(
      c(factor_heatmaps_combined_1q, factor_heatmaps_combined_2p,
        factor_heatmaps_combined_6p, factor_heatmaps_combined_16q),
      "results/fig_s16.pdf"
    )
  ),

  # Plot feature plots of interesting genes across samples grouped by cluster.
  tar_target(
    marker_gene_featureplots_by_cluster,
    plot_putative_marker_across_samples(unlist(interesting_genes), scna_seus, plot_type = FeaturePlot, group_by = "clusters")
  ),

  # --- cluster markers ---

  tar_target(
    cluster_markers,
    collect_all_markers(numbat_rds_files, "results/clusters.xlsx")
  ),

  tar_target(
    large_clusters,
    collect_clusters_from_seus(final_seus)
  ),

  # --- cluster comparisons ---

  tar_target(cluster_comparisons_by_phase_for_disctinct_clones,
    make_cluster_comparisons_by_phase_for_disctinct_clones(cluster_comparisons, overall_seus),
    pattern = map(cluster_comparisons),
    iteration = "list"
  ),

  # --- unfiltered numbat plots ---

  tar_target(large_numbat_pdfs,
    convert_numbat_pngs(numbat_rds_files),
    pattern = map(numbat_rds_files),
    iteration = "list"
  ),

  tar_target(unfiltered_numbat_expression,
    retrieve_numbat_plot_type(large_numbat_pdfs, "exp_roll_clust.pdf")
  ),

  tar_target(unfiltered_numbat_bulk_clones,
      retrieve_numbat_plot_type(large_numbat_pdfs, "bulk_clones_final.pdf")
  ),

  tar_target(fig_numbat_expression_smoothed,
    qpdf::pdf_combine(unfiltered_numbat_expression, "results/numbat_expression.pdf")
  ),

  # --- filtered numbat plots ---

  tar_target(filtered_numbat_pdfs,
    convert_numbat_pngs(numbat_rds_files),
    pattern = map(numbat_rds_files),
    iteration = "list"
  ),

  tar_target(filtered_numbat_expression,
    retrieve_numbat_plot_type(filtered_numbat_pdfs, "exp_roll_clust.pdf")
  ),

  tar_target(filtered_numbat_bulk_clones,
      retrieve_numbat_plot_type(filtered_numbat_pdfs, "bulk_clones_final.pdf")
  ),
  
  # --- low hypoxia numbat plots ---

  tar_target(low_hypoxia_numbat_pdfs,
    convert_numbat_pngs(numbat_rds_files),
    pattern = map(numbat_rds_files),
    iteration = "list"
  ),

  tar_target(low_hypoxia_numbat_expression,
    retrieve_numbat_plot_type(low_hypoxia_numbat_pdfs, "exp_roll_clust.pdf")
  ),

  tar_target(low_hypoxia_numbat_bulk_clones,
    retrieve_numbat_plot_type(low_hypoxia_numbat_pdfs, "bulk_clones_final.pdf")
  ),

  # For each sample, prefer the filtered bulk clones plot when available,
  # falling back to the unfiltered one. This ensures consistency with
  # fig_s03a_low_hypoxia_plots, which also prefers the filtered numbat run.
  tar_target(
    preferred_numbat_bulk_clones,
    {
      filt_ids <- str_extract(filtered_numbat_bulk_clones, "SRX[0-9]+")
      purrr::map_chr(unfiltered_numbat_bulk_clones, function(path) {
        sid <- str_extract(path, "SRX[0-9]+")
        filt_match <- filtered_numbat_bulk_clones[filt_ids == sid]
        if (length(filt_match) > 0) filt_match[[1]] else path
      })
    }
  ),

  tar_target(nb_paths_s06a,
    dir_ls("output/numbat_sridhar/", regexp = ".*SRX[0-9]+_numbat.rds", recurse = TRUE) |> sort()
  ),

  # Single pass per sample: one RDS load + 22 plotIdeogram calls generates all 3 suffix variants.
  tar_target(ideogram_res_s06a_multi,
    make_rb_scna_ideograms_multi(nb_paths_s06a, filter_midline = FALSE),
    pattern = map(nb_paths_s06a),
    iteration = "list",
    resources = .light_resources
  ),

  tar_target(ideogram_res_s06a_unfiltered,
    ideogram_res_s06a_multi[["unfiltered"]],
    pattern = map(ideogram_res_s06a_multi)
  ),

  tar_target(ideogram_res_s06a_filtered,
    ideogram_res_s06a_multi[["filtered"]],
    pattern = map(ideogram_res_s06a_multi)
  ),

  tar_target(nb_paths_s06a_filtered,
    dir_ls("output/numbat_sridhar_filtered/", regexp = ".*SRX[0-9]+_numbat.rds", recurse = TRUE) |> sort()
  ),

  tar_target(ideogram_res_s06a_low_hypoxia,
    ideogram_res_s06a_multi[["low_hypoxia"]],
    pattern = map(ideogram_res_s06a_multi)
  ),

  tar_target(fig_karyograms,
    {
      # targets flattens named list branch results: odd = plot paths, even = tables
      odd_idx <- seq(1, length(ideogram_res_s06a_unfiltered), by = 2)
      plot_paths <- as.character(ideogram_res_s06a_unfiltered[odd_idx])
      tables <- ideogram_res_s06a_unfiltered[odd_idx + 1] |>
        set_names(str_extract(plot_paths, "SRX[0-9]+"))
      writexl::write_xlsx(tables, "results/table_scna_karyotypes.xlsx")
      qpdf::pdf_combine(plot_paths, "results/fig_karyograms.pdf")
      list("results/fig_karyograms.pdf", "results/table_scna_karyotypes.xlsx")
    }
  ),

  tar_target(clone_trees_old,
    retrieve_numbat_plot_type(filtered_large_plot_files, "tree_filtered.pdf")
  ),

  tar_target(large_numbat_heatmap_files,
    retrieve_numbat_plot_type(large_numbat_pdfs, "panel_2.pdf")
  ),

  tar_target(large_numbat_heatmap_pdf,
    qpdf::pdf_combine(large_numbat_heatmap_files, "results/large_numbat_heatmaps.pdf")
  ),

  tar_target(large_numbat_sample_pdfs,
    reroute_done_to_results_pdf(numbat_rds_files, "_large"),
    pattern = map(numbat_rds_files),
    iteration = "list"
  ),

  tar_target(filtering_timelines,
    qpdf::pdf_combine(dir_ls("results", regexp = ".*SRX[0-9]+_filtering_timeline.pdf"), "results/filtering_timelines.pdf")
  ),

  # --- clone distribution and pearls ---

  tar_target(paired_clone_distribution_plots,
    calculate_clone_distribution(scna_seus, cluster_orders, pairwise = TRUE),
    iteration = "list"
  )
), # end list block before third tar_map

# clone_pearls_1q/2p/6p/16q — generated via tar_map over scna_map_values
# var_y: 1q and 16q use "phase_level"; 2p and 6p use "clusters"
tarchetypes::tar_map(
  values = scna_map_values,
  names  = "scna",
  tar_target(clone_pearls,
    { force(cluster_orders_sqlite); plot_clone_pearls(seus_sym, var_y = var_y) },
    pattern   = map(seus_sym),
    iteration = "list"
  )
),

list(
  tar_target(cluster_terms,
    enrich_by_cluster(scna_seus),
    pattern   = map(scna_seus),
    iteration = "list"
  ),

  tar_target(unpaired_clone_distribution_plots,
    calculate_clone_distribution(final_seus, cluster_orders, large_clone_comparisons = large_clone_comparisons, pairwise = FALSE),
    pattern = map(final_seus),
    iteration = "list"
  ),

  tar_target(
    cluster_scorecard,
    score_clusters_up_down(paired_clone_distribution_plots)
  ),

  tar_target(clusters_and_markers,
    plot_seu_clusters_and_markers(seus_low_hypoxia, cluster_orders),
    pattern = map(seus_low_hypoxia),
    iteration = "list"
  ),

  # --- clone trees ---

  tar_target(debranched_clone_tree_files,
    save_clone_tree_from_path(seus_low_hypoxia, numbat_rds_files, large_clone_simplifications, label = "_debranched_clone_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(seus_low_hypoxia),
    iteration = "list",
    cue = tar_cue(depend = FALSE)
  ),

  tar_target(debranched_clone_trees,
    plot_clone_tree_from_path(seus_low_hypoxia, numbat_rds_files, large_clone_simplifications, label = "_debranched_clone_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(seus_low_hypoxia),
    iteration = "list",
    cue = tar_cue(depend = FALSE)
  ),

  tar_target(
    debranched_clone_trees_file,
    qpdf::pdf_combine(debranched_clone_tree_files, "results/debranched_clone_trees.pdf")
  ),

  tar_target(unfiltered_clone_tree_files,
    save_clone_tree_from_path(unfiltered_seus, numbat_rds_files, large_clone_simplifications_per_sample, label = "_unfiltered_clone_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(unfiltered_seus, large_clone_simplifications_per_sample),
    iteration = "list",
    error = "null"
  ),

  # Clone trees with raw NUMBAT segment labels (no SCNA simplification applied).
  tar_target(unfiltered_clone_trees_segments_files,
    save_clone_tree_from_path(unfiltered_seus, numbat_rds_files, NULL, label = "_unfiltered_segment_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(unfiltered_seus),
    iteration = "list",
    error = "null"
  ),

  tar_target(
    unfiltered_clone_trees_segments_figure,
    qpdf::pdf_combine(unfiltered_clone_trees_segments_files, "results/unfiltered_clone_trees_segments.pdf")
  ),

  tar_target(filtered_clone_tree_files,
    save_clone_tree_from_path(filtered_seus, numbat_rds_files, large_clone_simplifications_per_sample, label = "_filtered_clone_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(filtered_seus, large_clone_simplifications_per_sample),
    iteration = "list",
    error = "null"
  ),

  tar_target(filtered_clone_trees_figure,
    qpdf::pdf_combine(filtered_clone_tree_files, "results/filtered_clone_trees.pdf")
  ),

  # Clone trees with raw NUMBAT segment labels (no SCNA simplification applied).
  tar_target(filtered_clone_trees_segments_files,
    save_clone_tree_from_path(filtered_seus, numbat_rds_files, NULL, label = "_filtered_segment_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(filtered_seus),
    iteration = "list",
    error = "null"
  ),

  tar_target(low_hypoxia_clone_tree_files,
    save_clone_tree_from_path(seus_low_hypoxia, numbat_rds_files, large_clone_simplifications_per_sample, label = "_low_hypoxia_clone_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(seus_low_hypoxia, large_clone_simplifications_per_sample),
    iteration = "list",
    error = "null"
  ),

  # Clone trees with raw NUMBAT segment labels (no SCNA simplification applied).
  tar_target(low_hypoxia_clone_trees_segments_files,
    save_clone_tree_from_path(seus_low_hypoxia, numbat_rds_files, NULL, label = "_low_hypoxia_segment_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(seus_low_hypoxia),
    iteration = "list",
    error = "null"
  ),

  tar_target(final_clone_tree_files,
    save_clone_tree_from_path(final_seus, numbat_rds_files, large_clone_simplifications_per_sample, label = "_clone_tree", legend = FALSE, horizontal = FALSE),
    pattern = map(final_seus, large_clone_simplifications_per_sample),
    iteration = "list"
  ),

  tar_target(final_clone_trees_file,
    qpdf::pdf_combine(final_clone_tree_files, "results/final_clone_trees.pdf")
  ),

  # --- sample-specific integration figures ---

  # integrated 1q fig for all 1q+ samples (thesis fig 4.3)
  tar_target(fig_1q_integrated,
    { force(cluster_orders_sqlite); plot_integrated_1q_fig(cluster_orders) }
  ),

  tar_target(fig_1q_integrated_v2,
    { force(cluster_orders_sqlite); plot_fig_04_afterall(cluster_orders) }
  ),

  # Sample-specific analyses of tumors with 1q+ subclones after integration.
  tar_target(fig_1q_sample_specific_integrated,
    { force(cluster_orders_sqlite); sample_specific_analyses_of_tumors_with_scna_subclones_after_integration(integrated_seus_1q, cluster_orders, "results/fig_1q_sample_specific_integrated.pdf") }
  ),

  # Sample-specific analyses of tumors with 16q- subclones after integration.
  tar_target(fig_16q_sample_specific_integrated,
    { force(cluster_orders_sqlite); sample_specific_analyses_of_tumors_with_scna_subclones_after_integration(integrated_seus_16q, cluster_orders, "results/fig_16q_sample_specific_integrated.pdf") }
  ),

  # Sample-specific analyses of tumors with 2p+ subclones after integration.
  tar_target(fig_2p_sample_specific_integrated,
    { force(cluster_orders_sqlite); sample_specific_analyses_of_tumors_with_scna_subclones_after_integration(integrated_seus_2p, cluster_orders, "results/fig_2p_sample_specific_integrated.pdf") }
  ),

  tar_target(fig_6p_sample_specific_integrated,
    { force(cluster_orders_sqlite); sample_specific_analyses_of_tumors_with_scna_subclones_after_integration(integrated_seus_6p, cluster_orders, "results/fig_6p_sample_specific_integrated.pdf") }
  ),

  tar_target(fig_subtype_markers, {
    # plot_fig_s25 saves to results/fig_s25.pdf but returns browseURL() result;
    # call it for the side effect and return the path explicitly.
    plot_fig_s25(subtype_markers = subtype_markers)
    "results/fig_s25.pdf"
  }),

  # 16q- subclones in multi-sample integration (Fig. 5): marker heatmap, CC scores,
  # faceted CC scores, clone distribution, proportion per cluster vs antecedent clones.
  tar_target(fig_16q_integrated,
    plot_fig_03(cluster_orders, plot_path = "results/fig_16q_integrated.pdf")
  ),

  tar_target(fig_1q_16q_combined,
    plot_fig_04_07(cluster_orders)
  ),

  tar_target(fig_2p_integrated,
    plot_fig_04_05(
      c("output/seurat/integrated_2p/seurat_2p_integrated_duo.rds",
        "output/seurat/SRX10264524_branch_6_filtered_seu.rds"),
      corresponding_clusters_enrichments[[6]],
      plot_path = "results/fig_2p_integrated.pdf",
      integrated_seu_paths = integrated_seus_2p,
      cluster_order = cluster_orders,
      large_clone_comparisons = large_clone_comparisons,
      scna_of_interest = "2p", width = 14, height = 10
    )
  ),

  tar_target(fig_6p_integrated,
    plot_fig_04_05(
      "output/seurat/integrated_6p/integrated_seu_6p_duo.rds",
      corresponding_clusters_enrichments[[7]],
      integrated_seu_paths = integrated_seus_6p,
      plot_path = "results/fig_6p_integrated.pdf",
      cluster_order = cluster_orders,
      large_clone_comparisons = large_clone_comparisons,
      scna_of_interest = "6p", width = 18, height = 10
    )
  ),

  tar_target(fig_1q_clone_diffex_within_clusters,  # Differential expression between integrated 1q clones within clusters
    plot_fig_s08()
  ),

  tar_target(fig_1q_cluster_diffex_of_interest,  # 1q+ cluster diffex of interest
    plot_fig_s09()
  ),

  tar_target(fig_16q_clone_diffex_within_clusters,  # Differential expression between integrated 16q clones within clusters
    plot_fig_s10()
  ),

  tar_target(fig_2p_clone_diffex_within_clusters,  # Differential expression between integrated 2p clones within clusters
    plot_fig_s20()
  ),

  # --- per-sample summary collation ---

  tar_target(sample_summaries,
    collate_sample_summary(
      ideogram_res_s06a_unfiltered,
      ideogram_res_s06a_filtered,
      ideogram_res_s06a_low_hypoxia,

      unfiltered_clone_tree_files,
      unfiltered_clone_trees_segments_files,

      filtered_clone_tree_files,
      filtered_clone_trees_segments_files,

      low_hypoxia_clone_tree_files,
      low_hypoxia_clone_trees_segments_files,

      numbat_heatmap_plots_unfiltered,
      numbat_heatmap_plots_subset,
      numbat_heatmap_plots_low_hypoxia,

      unfiltered_numbat_expression,
      filtered_numbat_expression,
      low_hypoxia_numbat_expression,

      unfiltered_numbat_bulk_clones,
      filtered_numbat_bulk_clones,
      low_hypoxia_numbat_bulk_clones,

      filtering_cell_counts_table = filtering_cell_counts_table
    ),
    pattern = map(unfiltered_clone_tree_files),
    iteration = "list",
    error = "null"
  ),

  tar_target(hypoxia_summaries,
    collate_hypoxia_summary(
      hypoxia_seus,
      hypoxia_score_plots,
      heatmap_collages_hypoxia,
      heatmap_collages_low_hypoxia,
      heatmap_collages_high_hypoxia
    ),
    pattern = map(
      hypoxia_seus,
      hypoxia_score_plots,
      heatmap_collages_hypoxia,
      heatmap_collages_low_hypoxia,
      heatmap_collages_high_hypoxia
    ),
    iteration = "list",
    error = "null"
  ),

  # --- pipeline notification ---

  tar_target(
    pipeline_notification,
    {
      # depend on figures_and_tables so this runs after the main outputs are ready
      invisible(figures_and_tables)
      tryCatch({
        send_pipeline_notification(subject = "Targets pipeline completed", body = NULL)
        TRUE
      }, error = function(e) {
        warning("Failed to send pipeline notification: ", e$message)
        FALSE
      })
    }
  ),

  # Sync all files from figures_and_tables to Google Drive via rclone.
  # Requires: module load rclone && rclone config (set gdrive_destination in pipeline_constants.R)
  tar_target(figures_and_tables_gdrive, {
    paths <- unlist(figures_and_tables)
    paths <- paths[nchar(paths) > 0 & !is.na(paths) & file.exists(paths)]

    files_txt <- tempfile()
    writeLines(paths, files_txt)
    on.exit(unlink(files_txt))

    ret <- system2(
      "rclone",
      c("copy", "--files-from", files_txt, ".", gdrive_destination, "--progress"),
      stdout = TRUE, stderr = TRUE
    )
    if (!is.null(attr(ret, "status")) && attr(ret, "status") != 0)
      stop("rclone failed:\n", paste(ret, collapse = "\n"))

    message("Synced ", length(paths), " files to ", gdrive_destination)
    paths
  })

)) # end list + end c()
